### ISSUE TITLE
Don't exclude tests on codeclimate

### ISSUE THREAD

**Issue by masone** [upfrontIO/apply-guides#6]
Mathieu, this repository distributes dotfiles across all of our projects. The [`.codeclimate.yml` currently excludes the test directory](https://github.com/upfrontIO/apply-guides/blob/master/static/.codeclimate.yml#L17), so they're not checked for linting errors. Can you remove that line please? 

When this is merged, have a look at the pull requests created. They will likely be failing because codeclimate now checks the test files. Can you fix the linting errors and make codeclimate happy again? :see_no_evil:

**Comment by mthpvg** [comment]
https://github.com/upfrontIO/apply-guides/pull/7
